//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UserRegistrationEntities : DbContext
    {
        public UserRegistrationEntities()
            : base("name=UserRegistrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Hobby> Hobbies { get; set; }
        public virtual DbSet<PersonInfo> PersonInfoes { get; set; }
        public virtual DbSet<PersonsInfo> PersonsInfoes { get; set; }
    
        public virtual ObjectResult<spGetAllInfo_Result> spGetAllInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetAllInfo_Result>("spGetAllInfo");
        }
    }
}
